spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/schema.sql
      data-locations: classpath:sql/data/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console